### ISSUE TITLE
Replacing 'master' branch with 'main' or similar wording

### ISSUE THREAD

**Issue by cruxicheiros** [Emersont1/TechNottingham.IT-Refurb#11]
I've just noticed while making a PR that the default branch of this repo is `master`, which is something a lot of people consider to be exclusionary: this is something [which even GitHub](https://www.zdnet.com/article/github-to-replace-master-with-alternative-term-to-avoid-slavery-references/) has decided they would like to change.

I think that especially because this is a community project, I would rather not implicitly signal to anyone that they are not welcome to pitch suggestions or work on this via the default branch name, and I think we should change it to `main` or similar before we wind up with lots of forks and branches that might make it trickier to change (if we started to use the repo itself to store information).

Only the current repo owner can do this, so I can only make this an issue, but here's the info on how to switch it out:

- Make a new branch cloned from `master` called `main`
- [Set the default branch to the new 'main' branch](https://help.github.com/en/github/administering-a-repository/setting-the-default-branch)
- Delete the original master branch

Cheers

**Comment by Emersont1** [comment]
fixed

**Comment by cruxicheiros** [comment]
great, thanks!
